local MONGO_DOCKER_PREFIX="aimldl"
local MONGO_DOCKER_IMG="mongouid"
local MONGO_DOCKER_CONTAINER_NAME="${MONGO_DOCKER_PREFIX}-${MONGO_DOCKER_IMG}"
## MongoDB configurations
local HOST_MONGODB_PORTS="27017"
local DOCKER_MONGODB_PORTS="27017"
local MONGODB_CONFIG_FILE="/codehub/config/mongod.conf"
# local MONGO_INITDB_ROOT_USERNAME=""
# local MONGO_INITDB_ROOT_PASSWORD=""
local MONGODB_USER=$(id -un mongodb)
local MONGODB_USER_ID=$(id -u mongodb)
local MONGODB_GRP=$(id -gn mongodb)
local MONGODB_GRP_ID=$(id -g mongodb)
#
local MONGODB_VOLUMES=""
# local MONGODB_VOLUMES="${MONGODB_VOLUMES} -v /aimldl-dat:/aimldl-dat "
MONGODB_VOLUMES="${MONGODB_VOLUMES} -v /aimldl-dat/data-mongodb:/data "
MONGODB_VOLUMES="${MONGODB_VOLUMES} -v /aimldl-dat/data-mongodb/db:/data/db "
MONGODB_VOLUMES="${MONGODB_VOLUMES} -v /aimldl-dat/data-mongodb/configdb:/data/configdb "
#
local MONGO_DB_PORTS=""
MONGO_DB_PORTS="${MONGO_DB_PORTS} -p ${HOST_MONGODB_PORTS}:${DOCKER_MONGODB_PORTS}"
#
## mongodb user fix
local MONGO_DOCKER_ENVVARS=""
MONGO_DOCKER_ENVVARS="${MONGO_DOCKER_ENVVARS} -e MONGODB_USER=${MONGODB_USER} "
MONGO_DOCKER_ENVVARS="${MONGO_DOCKER_ENVVARS} -e MONGODB_USER_ID=${MONGODB_USER_ID} "
MONGO_DOCKER_ENVVARS="${MONGO_DOCKER_ENVVARS} -e MONGODB_GRP=${MONGODB_GRP} "
MONGO_DOCKER_ENVVARS="${MONGO_DOCKER_ENVVARS} -e MONGODB_GRP_ID=${MONGODB_GRP_ID} "
