#!/bin/bash

bold=`tput bold`
bld=`tput smso`
nrml=`tput rmso`
reset=`tput reset`
red=$(tput setaf 1)
normal=$(tput sgr0)
rev=$(tput rev)
cyan_start="\033[36m"
cyan_stop="\033[0m"

#ver=`cat /proc/version | cut -f3 -d' '`
#str=`cat /proc/version | cut -f2 -d' '`
#echo $str $ver

#echo -e "${bold}${red}OS Release Name${normal}"
#cat /etc/redhat-release

processmgmnt=(pstree top iostat ps uname uptime w /sbin/lsmod /sbin/runlevel hostname)
memcmds=(vmstat free pmap top sar time as cat One)
systeminfo=(uname)
cmdarry=(processmgmnt memcmds systeminfo)
PS3="Choose (1-${#cmdarry[*]}):"
echo "Choose from the list below."
select cmdtypname in ${cmdarry[@]}
do
	case  $cmdtypname in 
		processmgmnt)
				PS3="Choose (1-${#processmgmnt[*]}):"
				select optn in ${processmgmnt[@]}
				do
					echo "Executing as shell command..."
					$optn
					break
				done
				;;
		     memcmds)	
				PS3="Choose (1-${#memcmds[*]}):"
                                select optn in ${memcmds[@]}
                                do
					echo "Executing as shell command..."
					$optn
					break
                                done
				;;
		     systeminfo)	
				PS3="Choose (1-${#systeminfo[*]}):"
                                select optn in ${systeminfo[@]}
                                do
					echo "Executing as shell command..."
					$optn
					break
                                done
				;;
			   *)
				;;
	esac	
	if [ "$cmdtypname" = "" -o "$optn" = "" ]; then
        	echo "Error in entry."
	        exit 1
	fi
	break
done
