#!/bin/bash

PS3="Choose (1-5):"
echo "Choose from the list below."
select name in red green blue yellow magenta
do
	break
done
if [ "$name" = "" ]; then
	echo "Error in entry."
	exit 1
fi
echo "You chose $name."

