#!/bin/bash

bold=`tput bold`
bld=`tput smso`
nrml=`tput rmso`
reset=`tput reset`
red=$(tput setaf 1)
normal=$(tput sgr0)
rev=$(tput rev)
cyan_start="\033[36m"
cyan_stop="\033[0m"

ver=`cat /proc/version | cut -f3 -d' '`
str=`cat /proc/version | cut -f2 -d' '`
echo $str $ver

echo -e "${bold}${red}OS Release Name${normal}"
cat /etc/redhat-release
