git clone https://github.com/sercant/android-segmentation-app.git
git clone https://github.com/mangalbhaskar/codehub.git
git clone https://github.com/mangalbhaskar/cloudy_vision.git
git clone https://github.com/mangalbhaskar/cloudy_vision_web.git
git clone https://github.com/ductm104/echocardiography.git
git clone https://github.com/mangalbhaskar/keras-retinanet
git clone https://github.com/amir-abdi/keras_to_tensorflow.git
git clone https://github.com/nikhilbv/lanenet-lane-detection.git
git clone https://github.com/mapbox/mapbox-vision-android.git
git clone https://github.com/mangalbhaskar/Mask_RCNN.git
git clone https://github.com/gustavz/Mobile_Mask_RCNN.git
git clone https://github.com/nikhilbv/TuSimple-lane-classes.git
git clone https://github.com/ucbdrive/bdd-data.git
git clone https://github.com/nikhilbv/Cascade-LD.git
git clone https://github.com/cardwing/Codes-for-Lane-Detection.git
git clone https://github.com/pjreddie/darknet
git clone https://github.com/zhengshoujian/darknet-yolo-segmentation.git
# git clone https://github.com/facebookresearch/detectron2.git //github.com/saqibmobin/detectron2.git
git clone https://github.com/mangalbhaskar/aimldl.git
git clone https://github.com/nikhilbv/simple-keras-rest-api.git
git clone https://github.com/ShuLiu1993/PANet.git
git clone https://github.com/XingangPan/seg_label_generate.git
git clone https://github.com/nikhilbv/tusimple-benchmark.git
git clone https://github.com/SeokjuLee/VPGNet.git
